import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import App from '../App'
import { PalabraStorage, DEFAULT_SETTINGS } from '../data/storage'
import { spanishFixture } from './fixtures'
import { toLocalDate } from '../domain/stats'
import { advancePractice, createPracticeQueue } from '../domain/practiceQueue'
import { scheduleSpanishReview } from './course'

const clients:PalabraStorage[]=[]
afterEach(()=>{cleanup();vi.restoreAllMocks();clients.forEach(c=>c.close())})
async function setup(prepare?:(db:PalabraStorage)=>Promise<void>, words=[spanishFixture()]) {
  const db=new PalabraStorage(`es-ui-${crypto.randomUUID()}`,{vocabularySeeds:{es:words,en:[]}})
  clients.push(db);await db.saveSettings({...DEFAULT_SETTINGS,spanishDailyGoal:50})
  await prepare?.(db)
  const user=userEvent.setup()
  render(<MemoryRouter initialEntries={['/today']}><App storageClient={db}/></MemoryRouter>)
  await screen.findByRole('heading',{name:'今天'})
  return {db,user}
}
describe('Spanish contextual course',()=>{
  it.each(['','hablo'])('reveals full Spanish answer from input "%s", restores and requires independent spelling',async(input)=>{
    const {db,user}=await setup(undefined,[spanishFixture(),spanishFixture('es:second','duermo','dormir')])
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    const answerInput=await screen.findByRole('textbox',{name:'填写缺少的西语词'})
    if(input)await user.type(answerInput,input)
    await user.dblClick(screen.getByRole('button',{name:'不认识'}))
    expect(await screen.findByRole('region',{name:'完整答案'})).toHaveTextContent('hablo')
    expect(screen.getByRole('region',{name:'完整答案'})).toHaveFocus()
    expect(screen.getByRole('region',{name:'西语句子填词'})).toHaveTextContent('Yo hablo español con mi vecina.')
    expect(screen.queryByLabelText('拼写错误对比')).not.toBeInTheDocument()
    expect((await db.getActiveSession('es'))?.spanish?.feedback).toMatchObject({correct:false,answerRevealed:true})
    expect((await db.getAllProgress('es'))[0]).toMatchObject({wordId:'es:test:hablo',stage:0,status:'learning'})
    cleanup();render(<MemoryRouter initialEntries={['/study']}><App storageClient={db}/></MemoryRouter>)
    expect(await screen.findByRole('region',{name:'完整答案'})).toHaveTextContent('hablo')
    await user.click(screen.getByRole('button',{name:'重新拼写'}))
    expect(screen.queryByRole('region',{name:'完整答案'})).not.toBeInTheDocument()
    expect(screen.getByRole('textbox',{name:'填写缺少的西语词'})).toHaveValue('')
    expect(screen.getByRole('region',{name:'西语句子填词'})).toHaveTextContent('____')
    await user.type(screen.getByRole('textbox',{name:'填写缺少的西语词'}),'hablo')
    await user.click(screen.getByRole('button',{name:'检查答案'}))
    await user.click(await screen.findByRole('button',{name:'继续'}))
    const saved=(await db.getActiveSession('es'))!
    expect(saved.practice?.delayed).toEqual([{wordId:'es:test:hablo',remaining:3}])
    expect(saved.practice?.firstAnswers['es:test:hablo']).toBe(false)
  })
  it('keeps a Spanish reveal hidden on save failure and retains skip priority after reveal',async()=>{
    const {db,user}=await setup()
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    await screen.findByRole('button',{name:'不认识'})
    vi.spyOn(db,'commitSpanishStep').mockRejectedValueOnce(new Error('quota'))
    await user.click(screen.getByRole('button',{name:'不认识'}))
    expect(await screen.findByRole('alert')).toHaveTextContent('保存失败')
    expect(screen.queryByRole('region',{name:'完整答案'})).not.toBeInTheDocument()
    await user.click(screen.getByRole('button',{name:'不认识'}))
    await screen.findByRole('region',{name:'完整答案'})
    await user.click(screen.getByRole('button',{name:'跳过，稍后复习'}))
    expect((await db.getAllProgress('es'))[0]).toMatchObject({wordId:'es:test:hablo',reviewPriority:'skipped',skipReview:false})
  })
  it.each([
    ['本句：再见；感叹词 · 不变形','感叹词 · 不变形','再见',''],
    ['原形 hablar；本句：说；讲话；陈述式现在时 · 第一人称单数（yo）','陈述式现在时 · 第一人称单数（yo）','说；讲话','原形 hablar'],
    ['本题使用以 -í 结尾的地点副词；本句：这里；副词 · 不变形','副词 · 不变形','这里','本题使用以 -í 结尾的地点副词'],
    ['说（西班牙语）','陈述式现在时 · 第一人称单数（yo）','说（西班牙语）',''],
  ])('promotes contextual meaning without losing saved cue details: %s',async(cue,grammar,meaning,instruction)=>{
    const word=spanishFixture()
    word.spanishData!.grammarLabel=grammar
    word.spanishData!.cloze.cueZh=cue
    const {user}=await setup(undefined,[word])
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    const prompt=within(await screen.findByRole('region',{name:'西语句子填词'}))
    expect(prompt.getByRole('heading',{level:1,name:meaning})).toBeInTheDocument()
    expect(prompt.getAllByText(grammar,{exact:true})).toHaveLength(1)
    if(instruction)expect(prompt.getByText(instruction,{exact:true})).toBeInTheDocument()
    expect(prompt.queryByText(/填入：|本句：/)).not.toBeInTheDocument()
    expect(prompt.getByText(/____/)).not.toHaveTextContent('hablo')
    await user.type(screen.getByRole('textbox',{name:'填写缺少的西语词'}),'ha')
    await user.click(screen.getByRole('button',{name:'结束'}))
    await user.click(await screen.findByRole('button',{name:'继续本组'}))
    expect(await screen.findByRole('heading',{level:1,name:meaning})).toBeInTheDocument()
    expect(screen.getByRole('textbox',{name:'填写缺少的西语词'})).toHaveValue('ha')
  })
  it('reconciles pre-upgrade saved feedback and known earlier practice exactly once on completion',async()=>{
    const words=[spanishFixture(),spanishFixture('es:prior','duermo','dormir'),...Array.from({length:10},(_,i)=>spanishFixture(`es:new${i}`,'hablo',`f${i}`))]
    const {db,user}=await setup(async db=>{
      await db.saveSettings({...DEFAULT_SETTINGS,spanishDailyGoal:10,enableChoice:false,enableSpelling:true})
      const priorTime=new Date(Date.now()-1000),start=new Date(Date.now()-60000)
      await db.putProgress(scheduleSpanishReview(undefined,words[1].id,'remembered',priorTime))
      const queue=createPracticeQueue([words[0].id])
      await db.saveActiveSession({id:'active-session:es',language:'es',wordIds:[words[0].id,words[1].id],newWordIds:[words[0].id,words[1].id],reviewWordIds:[],assignedNewCount:2,assignedReviewCount:0,currentIndex:0,phase:'quiz',correctCount:0,answeredCount:0,startedAt:start.toISOString(),practice:queue,revision:0,quizFeedback:{wordId:words[0].id,correct:true,selected:'hablo',nextPractice:advancePractice(queue,true)}})
    },words)
    await user.click(screen.getByRole('button',{name:'继续本组'}))
    await user.click(await screen.findByRole('button',{name:'继续'}))
    expect(Object.keys((await db.getSpanishDay(toLocalDate(new Date()))).entries).sort()).toEqual([words[0].id,words[1].id].sort())
    await user.click(await screen.findByRole('button',{name:'开始下一组'}))
    expect((await db.getActiveSession('es'))?.wordIds).toHaveLength(8)
    await user.click(await screen.findByRole('button',{name:'结束'}))
    await user.click(await screen.findByRole('link',{name:'进度'}))
    expect(await screen.findByText('共学习 2 次')).toBeInTheDocument()
  })
  it('keeps next groups review-only and does not offer new words after reviews finish',async()=>{
    const reviews=Array.from({length:11},(_,i)=>spanishFixture(`es:review:${i}`))
    const fresh=spanishFixture('es:fresh')
    const {db,user}=await setup(async db=>{
      for(const word of reviews)await db.putProgress(scheduleSpanishReview(undefined,word.id,'remembered',new Date('2020-01-01T00:00:00Z')))
    },[...reviews,fresh])
    await user.click(screen.getByRole('button',{name:'只复习到期词'}))
    for(let i=0;i<10;i++) {
      await user.type(await screen.findByRole('textbox',{name:'填写缺少的西语词'}),'hablo')
      await user.click(screen.getByRole('button',{name:'检查答案'}))
      await user.click(await screen.findByRole('button',{name:'继续'}))
    }
    await user.click(await screen.findByRole('button',{name:'开始下一组'}))
    const last=await db.getActiveSession('es')
    expect(last?.mode).toBe('review')
    expect(last?.newWordIds).toEqual([])
    expect(last?.wordIds).toHaveLength(1)
    await user.type(await screen.findByRole('textbox',{name:'填写缺少的西语词'}),'hablo')
    await user.click(screen.getByRole('button',{name:'检查答案'}))
    await user.click(await screen.findByRole('button',{name:'继续'}))
    expect(await screen.findByText('本组练习完成')).toBeInTheDocument()
    expect(screen.queryByRole('button',{name:'开始下一组'})).not.toBeInTheDocument()
  })
  it('switches from a completed legacy session to cloze for its next group',async()=>{
    const words=[spanishFixture(),...Array.from({length:11},(_,i)=>spanishFixture(`es:test:${i}`,'duermo',`family${i}`))]
    const {user,db}=await setup(async db=>{
      await db.saveSettings({...DEFAULT_SETTINGS,spanishDailyGoal:10,enableChoice:false,enableSpelling:true})
      await db.saveActiveSession({id:'active-session:es',language:'es',wordIds:[words[0].id],newWordIds:[words[0].id],reviewWordIds:[],currentIndex:0,phase:'quiz',correctCount:0,answeredCount:0,startedAt:'2026-09-26T10:00:00Z',practice:createPracticeQueue([words[0].id]),revision:0})
    },words)
    await user.click(screen.getByRole('button',{name:'继续本组'}))
    await user.type(await screen.findByRole('textbox',{name:'西班牙语'}),'hablo')
    await user.click(screen.getByRole('button',{name:'检查答案'}))
    await user.click(await screen.findByRole('button',{name:'继续'}))
    expect(Object.keys((await db.getSpanishDay(toLocalDate(new Date()))).entries)).toEqual([words[0].id])
    await user.click(await screen.findByRole('button',{name:'开始下一组'}))
    expect(await screen.findByRole('textbox',{name:'填写缺少的西语词'})).toBeInTheDocument()
    expect((await db.getActiveSession('es'))?.spanish?.version).toBe(1)
    expect((await db.getActiveSession('es'))?.wordIds).toHaveLength(9)
    await user.click(screen.getByRole('button',{name:'结束'}))
    await user.click(await screen.findByRole('link',{name:'进度'}))
    expect(await screen.findByText('共学习 1 次')).toBeInTheDocument()
  })
  it('updates today immediately after leaving a partially answered legacy session',async()=>{
    const word=spanishFixture()
    const {user}=await setup(async db=>{
      await db.saveSettings({...DEFAULT_SETTINGS,enableChoice:false,enableSpelling:true})
      await db.saveActiveSession({id:'active-session:es',language:'es',wordIds:[word.id],newWordIds:[word.id],reviewWordIds:[],currentIndex:0,phase:'quiz',correctCount:0,answeredCount:0,startedAt:'2026-09-26T10:00:00Z',practice:createPracticeQueue([word.id]),revision:0})
    })
    await user.click(screen.getByRole('button',{name:'继续本组'}))
    await user.type(await screen.findByRole('textbox',{name:'西班牙语'}),'hablo')
    await user.click(screen.getByRole('button',{name:'检查答案'}))
    await screen.findByRole('button',{name:'继续'})
    await user.click(screen.getByRole('button',{name:'结束'}))
    expect(await screen.findByText('已练习 1 个')).toBeInTheDocument()
  })
  it('keeps the displayed prompt aligned with a committed step when later reads fail',async()=>{
    const {db,user}=await setup(undefined,[spanishFixture(),spanishFixture('es:test:duermo','duermo','dormir')])
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    await user.type(await screen.findByRole('textbox',{name:'填写缺少的西语词'}),'hablo')
    await user.click(screen.getByRole('button',{name:'检查答案'}))
    await screen.findByRole('button',{name:'继续'})
    vi.spyOn(db,'getSpanishDays').mockRejectedValue(new Error('read failed'))
    await user.click(screen.getByRole('button',{name:'继续'}))
    expect(await screen.findByRole('textbox',{name:'填写缺少的西语词'})).toHaveValue('')
    expect(screen.queryByText('拼写正确')).not.toBeInTheDocument()
    expect((await db.getAllProgress('es')).map(p=>p.wordId)).toEqual(['es:test:hablo'])
    expect((await db.getActiveSession('es'))?.practice?.pendingIds[0]).toBe('es:test:duermo')
  })
  it('saves the visible dirty draft along with a successful hint after recovery',async()=>{
    const {db,user}=await setup()
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    const input=await screen.findByRole('textbox',{name:'填写缺少的西语词'})
    vi.spyOn(db,'commitSpanishStep').mockRejectedValueOnce(new Error('full'))
    await user.type(input,'h');await screen.findByRole('alert')
    await user.click(screen.getByRole('button',{name:'提示字母'}))
    await screen.findByText('h____')
    await user.click(screen.getByRole('button',{name:'结束'}))
    await user.click(await screen.findByRole('button',{name:'继续本组'}))
    expect(await screen.findByRole('textbox',{name:'填写缺少的西语词'})).toHaveValue('h')
    expect((await db.getActiveSession('es'))?.spanish?.draft).toBe('h')
  })
  it('keeps an existing legacy Spanish session on its old reveal-and-rate flow',async()=>{
    const {user}=await setup(async db=>{
      const word=spanishFixture()
      await db.saveActiveSession({id:'active-session:es',language:'es',wordIds:[word.id],newWordIds:[word.id],reviewWordIds:[],currentIndex:0,phase:'learn',correctCount:0,answeredCount:0,startedAt:'2026-09-26T10:00:00Z',practice:createPracticeQueue([word.id]),revision:0})
    })
    await user.click(screen.getByRole('button',{name:'继续本组'}))
    expect(await screen.findByRole('button',{name:'点击查看释义'})).toBeInTheDocument()
    expect(screen.queryByRole('textbox',{name:'填写缺少的西语词'})).not.toBeInTheDocument()
  })
  it('changes only the Spanish total goal and keeps shared English new-word settings',async()=>{
    const {db,user}=await setup()
    await user.click(screen.getByRole('link',{name:'设置'}))
    expect(await screen.findByRole('heading',{name:'西语每日总量'})).toBeInTheDocument()
    await user.click(screen.getByRole('button',{name:'30'}))
    await waitFor(async()=>expect((await db.getSettings()).spanishDailyGoal).toBe(30))
    expect((await db.getSettings()).dailyNewWords).toBe(10)
  })
  it('marks only the current grammatical unit fluent',async()=>{
    const {db,user}=await setup()
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    await user.click(await screen.findByRole('button',{name:'标为熟练'}))
    await screen.findByText('本组练习完成')
    const progress=await db.getAllProgress('es')
    expect(progress).toHaveLength(1)
    expect(progress[0]).toMatchObject({wordId:'es:test:hablo',skipReview:true})
  })
  it('releases pending controls if a draft failure cancels a queued hint',async()=>{
    const {db,user}=await setup()
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    const input=await screen.findByRole('textbox',{name:'填写缺少的西语词'})
    let rejectSave!:(error:Error)=>void
    vi.spyOn(db,'commitSpanishStep').mockImplementationOnce(()=>new Promise((_resolve,reject)=>{rejectSave=reject}))
    await user.type(input,'h')
    await user.click(screen.getByRole('button',{name:'提示字母'}))
    rejectSave(new Error('quota'))
    await screen.findByRole('alert')
    await waitFor(()=>expect(screen.getByRole('button',{name:'提示字母'})).toBeEnabled())
  })
  it('does not lose unsaved input or leave the page when storage fails',async()=>{
    const {db,user}=await setup()
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    const input=await screen.findByRole('textbox',{name:'填写缺少的西语词'})
    vi.spyOn(db,'commitSpanishStep').mockRejectedValue(new DOMException('full','QuotaExceededError'))
    await user.type(input,'h')
    await screen.findByRole('alert')
    expect(input).toHaveValue('h')
    await user.click(screen.getByRole('button',{name:'结束'}))
    expect(screen.getByRole('textbox',{name:'填写缺少的西语词'})).toBeInTheDocument()
  })
  it('restores a competing tab update without overwriting its input or double counting',async()=>{
    const {db,user}=await setup()
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    await screen.findByRole('textbox',{name:'填写缺少的西语词'})
    const saved=(await db.getActiveSession('es'))!
    await db.commitSpanishStep({...saved,revision:1,spanish:{...saved.spanish!,draft:'externo'}})
    await user.type(screen.getByRole('textbox',{name:'填写缺少的西语词'}),'h')
    await screen.findByRole('alert')
    expect((await db.getActiveSession('es'))?.spanish?.draft).toBe('externo')
    expect(screen.getByRole('textbox',{name:'填写缺少的西语词'})).toHaveValue('externo')
    expect((await db.getSpanishDay(toLocalDate(new Date()))).entries).toEqual({})
  })
  it('shows an incorrect form and immediately retries before finishing the group',async()=>{
    const {db,user}=await setup()
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    await user.type(await screen.findByRole('textbox',{name:'填写缺少的西语词'}),'habló')
    await user.click(screen.getByRole('button',{name:'检查答案'}))
    expect(await screen.findByLabelText('拼写错误对比')).toBeInTheDocument()
    await user.click(screen.getByRole('button',{name:'立即重做'}))
    expect(await screen.findByRole('textbox',{name:'填写缺少的西语词'})).toHaveValue('')
    expect((await db.getAllProgress('es'))[0].correctCount).toBe(0)
    expect(Object.keys((await db.getSpanishDay(toLocalDate(new Date()))).entries)).toHaveLength(1)
  })
  it('shows the combined target, then a cloze with no exposed answer, persists draft on exit',async()=>{
    const {db,user}=await setup()
    expect(screen.getByText('新词与复习合计')).toBeInTheDocument()
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    const input=await screen.findByRole('textbox',{name:'填写缺少的西语词'})
    expect(screen.queryByText('hablo')).not.toBeInTheDocument()
    expect(screen.getByText('我和邻居说西班牙语。')).toBeInTheDocument()
    await user.type(input,'ha')
    await user.click(screen.getByRole('button',{name:'结束'}))
    expect((await db.getActiveSession('es'))?.spanish?.draft).toBe('ha')
    await user.click(await screen.findByRole('button',{name:'继续本组'}))
    expect(await screen.findByRole('textbox',{name:'填写缺少的西语词'})).toHaveValue('ha')
  })
  it('preserves hints, requires independent recall, and completes with per-word progress',async()=>{
    const {db,user}=await setup()
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    await user.click(await screen.findByRole('button',{name:'提示字母'}))
    expect(await screen.findByText('h____')).toBeInTheDocument()
    await user.type(screen.getByRole('textbox',{name:'填写缺少的西语词'}),'hablo')
    await user.click(screen.getByRole('button',{name:'检查答案'}))
    expect(await screen.findByText('稍后需要再无提示拼对一次。')).toBeInTheDocument()
    await user.click(screen.getByRole('button',{name:'继续'}))
    await user.type(await screen.findByRole('textbox',{name:'填写缺少的西语词'}),'hablo')
    await user.click(screen.getByRole('button',{name:'检查答案'}))
    await user.click(await screen.findByRole('button',{name:'继续'}))
    await screen.findByText('本组练习完成')
    expect(await db.getActiveSession('es')).toBeUndefined()
    expect(Object.keys((await db.getSpanishDay(toLocalDate(new Date()))).entries)).toHaveLength(1)
    expect((await db.getAllProgress('es'))[0].language).toBe('es')
  })
  it('skips immediately into priority review without calling it mastered',async()=>{
    const {db,user}=await setup()
    await user.click(screen.getByRole('button',{name:'开始今天的学习'}))
    await user.click(await screen.findByRole('button',{name:'跳过，稍后复习'}))
    await screen.findByText('本组练习完成')
    await waitFor(async()=>expect((await db.getAllProgress('es'))[0].reviewPriority).toBe('skipped'))
    expect((await db.getAllProgress('es'))[0].skipReview).toBe(false)
  })
})
