begin;
select no_plan();
update palabra_private.feature_settings set enabled=true;
insert into auth.users(id) values ('51000000-0000-0000-0000-000000000001'),('51000000-0000-0000-0000-000000000002'),('51000000-0000-0000-0000-000000000003');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"51000000-0000-0000-0000-000000000001"}',true);
select public.palabra_register('甲',encode(sha256(convert_to(repeat('d',64),'UTF8')),'hex'),gen_random_uuid());
select public.palabra_create_group('权限组',encode(sha256(convert_to(repeat('d',32),'UTF8')),'hex'),gen_random_uuid());
select set_config('test.binding',(public.palabra_self()->'data'->'binding')::text,true);
reset role;
update public.palabra_memberships set joined_at=now()-interval '2 days' where id=(current_setting('test.binding')::jsonb->>'membershipId')::uuid;
set local role authenticated;
select set_config('test.payload',jsonb_build_object('membershipId',current_setting('test.binding')::jsonb->>'membershipId','membershipGeneration',1,'deviceGeneration',1,
  'date',(now() at time zone 'Asia/Shanghai')::date,'language','en','version',1,'goal',10,'newCount',5,'reviewCount',2,'skippedCount',1,'lastPracticedAt',now())::text,true);
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb)->>'ok','true','old device snapshot');
select public.palabra_sync_summary(current_setting('test.payload')::jsonb||jsonb_build_object('date',((now()-interval '1 day') at time zone 'Asia/Shanghai')::date,'lastPracticedAt',now()-interval '1 day'));
select set_config('request.jwt.claims','{"sub":"51000000-0000-0000-0000-000000000002"}',true);
select public.palabra_register('朋友',repeat('8',64),gen_random_uuid());
select public.palabra_join_group(repeat('d',32),gen_random_uuid());
select is(jsonb_array_length(public.palabra_activity('2000-01-01')->'data'->'summaries'),1,'new reader cannot fetch earlier date');
select set_config('request.jwt.claims','{"sub":"51000000-0000-0000-0000-000000000003"}',true);
select public.palabra_recover(repeat('d',64),repeat('9',64),'61000000-0000-0000-0000-000000000001');
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb||'{"deviceGeneration":2,"newCount":3,"reviewCount":4,"goal":20}')->>'ok','true','restored device snapshot');
select is(public.palabra_activity(null)->'data'->'summaries'->0->>'newCount','5','new counts max, not sum');
select is(public.palabra_activity(null)->'data'->'summaries'->0->>'reviewCount','4','review counts max');
select is(public.palabra_activity(null)->'data'->'summaries'->0->>'goal','10','first goal retained');
select is(public.palabra_activity(null)->'data'->'summaries'->0->>'conservative','true','conservative label retained');
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb)->>'code','STALE_BINDING','old generation invalid even with new JWT');
select set_config('request.jwt.claims','{"sub":"51000000-0000-0000-0000-000000000001"}',true);
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb)->>'code','DEVICE_REPLACED','old JWT upload denied');
select is(public.palabra_activity(null)->>'code','DEVICE_REPLACED','old JWT read denied');
select set_config('request.jwt.claims','{"sub":"51000000-0000-0000-0000-000000000003"}',true);
select is(public.palabra_publish_note((current_setting('test.binding')::jsonb->>'membershipId')::uuid,1,2,(now() at time zone 'Asia/Shanghai')::date,1,'<script>alert(1)</script> '' ; --')->>'ok','true','stored as text');
select is(public.palabra_activity(null)->'data'->'notes'->0->>'text','<script>alert(1)</script> '' ; --','text not interpreted by SQL');
reset role;
update palabra_private.operation_receipts set created_at=now()-interval '31 days' where operation_id='61000000-0000-0000-0000-000000000001';
set local role authenticated;
select is(public.palabra_operation('61000000-0000-0000-0000-000000000001')->>'code','NOT_FOUND','expired receipts unavailable before cleanup');
reset role;
select lives_ok('select palabra_private.cleanup()','maintenance executes locally');
select ok(not has_function_privilege('authenticated','palabra_private.cleanup()','EXECUTE'),'maintenance is private');
select * from finish();
rollback;
