begin;
select no_plan();
select has_function('public','palabra_sync_summary',array['jsonb']);
update palabra_private.feature_settings set enabled=true;
insert into auth.users(id) values ('50000000-0000-0000-0000-000000000001'),('50000000-0000-0000-0000-000000000002');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"50000000-0000-0000-0000-000000000001"}',true);
select public.palabra_register('甲',repeat('6',64),gen_random_uuid());
select public.palabra_create_group('打卡组',encode(sha256(convert_to(repeat('c',32),'UTF8')),'hex'),gen_random_uuid());
select set_config('test.binding',(public.palabra_self()->'data'->'binding')::text,true);
select set_config('test.payload',jsonb_build_object('membershipId',current_setting('test.binding')::jsonb->>'membershipId','membershipGeneration',1,'deviceGeneration',1,
  'date',(now() at time zone 'Asia/Shanghai')::date,'language','en','version',1,'goal',10,'newCount',2,'reviewCount',3,'skippedCount',1,'lastPracticedAt',now())::text,true);
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb)->>'ok','true','first snapshot');
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb)->>'ok','true','same snapshot idempotent');
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb||'{"newCount":9}')->>'code','VERSION_CONFLICT','changed same-version rejected');
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb||'{"wordIds":["en:apple"]}')->>'code','INVALID_PAYLOAD','no extra fields accepted');
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb||jsonb_build_object('membershipId',gen_random_uuid()))->>'code','STALE_BINDING','cannot choose another membership');
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb||'{"version":2,"newCount":5,"skippedCount":0}')->>'ok','true','newer snapshot');
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb)->'data'->>'acceptedVersion','2','old version ignored');
select is((public.palabra_activity(null)->'data'->'summaries'->0->>'newCount')::integer,5,'never adds duplicate snapshots');
select is(public.palabra_sync_summary(current_setting('test.payload')::jsonb||jsonb_build_object('date',(now() at time zone 'Asia/Shanghai')::date-30))->>'code','DATE_OUT_OF_RANGE','past retention rejected');
select is(public.palabra_publish_note((current_setting('test.binding')::jsonb->>'membershipId')::uuid,1,1,(now() at time zone 'Asia/Shanghai')::date,1,repeat('🙂',100))->>'ok','true','100 Unicode characters');
select is(public.palabra_publish_note((current_setting('test.binding')::jsonb->>'membershipId')::uuid,1,1,(now() at time zone 'Asia/Shanghai')::date,2,'')->>'ok','true','clear content with version tombstone');
select is(public.palabra_publish_note((current_setting('test.binding')::jsonb->>'membershipId')::uuid,1,1,(now() at time zone 'Asia/Shanghai')::date,1,'old')->'data'->>'acceptedVersion','2','old note cannot reappear');
select is(public.palabra_publish_note((current_setting('test.binding')::jsonb->>'membershipId')::uuid,1,1,(now() at time zone 'Asia/Shanghai')::date,3,repeat('🙂',101))->>'code','INVALID_INPUT','101 rejected');
select is(public.palabra_send_nudge((current_setting('test.binding')::jsonb->>'profileId')::uuid,'cheer',gen_random_uuid())->>'code','INVALID_TARGET','no self nudge');
select set_config('request.jwt.claims','{"sub":"50000000-0000-0000-0000-000000000002"}',true);
select public.palabra_register('乙',repeat('7',64),gen_random_uuid());
select is(public.palabra_activity(null)->>'code','NOT_MEMBER','outsider activity rejected');
select public.palabra_join_group(repeat('c',32),gen_random_uuid());
select is(public.palabra_send_nudge((current_setting('test.binding')::jsonb->>'profileId')::uuid,'cheer',gen_random_uuid())->>'ok','true','same group cheer');
select is(public.palabra_send_nudge((current_setting('test.binding')::jsonb->>'profileId')::uuid,'cheer',gen_random_uuid())->>'code','ALREADY_SENT','daily limit');
select set_config('request.jwt.claims','{"sub":"50000000-0000-0000-0000-000000000001"}',true);
select is(jsonb_array_length(public.palabra_activity(null)->'data'->'nudges'),1,'recipient sees nudge');
select public.palabra_update_profile('甲',false,gen_random_uuid());
select is(public.palabra_delete_profile(gen_random_uuid())->>'code','OWNER_REQUIRED','owner cannot delete leaving orphan');
select set_config('request.jwt.claims','{"sub":"50000000-0000-0000-0000-000000000002"}',true);
select is(public.palabra_send_nudge((current_setting('test.binding')::jsonb->>'profileId')::uuid,'remind',gen_random_uuid())->>'code','NUDGES_DISABLED','preference immediate');
select is(public.palabra_delete_profile('60000000-0000-0000-0000-000000000001')->>'ok','true','delete own business profile');
select is(public.palabra_delete_profile('60000000-0000-0000-0000-000000000001')->>'ok','true','delete receipt replay');
select set_config('request.jwt.claims','{"sub":"50000000-0000-0000-0000-000000000001"}',true);
select is(jsonb_array_length(public.palabra_activity(null)->'data'->'nudges'),0,'deleted member nudges removed');
select * from finish();
rollback;
